[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "teledrive"
version = "2.0.0"
description = "High-Performance, Fault-Tolerant Cloud Storage Engine Powered by Telegram."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "telethon>=1.36.0",
    "rich>=13.0.0",
]

[project.scripts]
teledrive = "teledrive.cli:main"
telesync = "teledrive.cli:main"

[tool.setuptools]
packages = ["teledrive", "telesync"]
